name: C++ CI

on:
  push:
      branches: [ main ]

jobs:
  build:
    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ cmake make qt6-base-dev clang-format libgl1-mesa-dev libglvnd-dev

    - name: Build
      run: cmake -B build/ -S . && make -C build/ -j$(nproc)
