name: C++ CI

on:
  push:
      branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y \
        g++ \
        cmake \
        make \
        libgl1-mesa-dev \
        libglvnd-dev \
        qt6-base-dev \
        clang-format \
        curl \
        libcrypto++-dev

    - name: Build
      run: cmake -B build/ -S . && make -C build/ -j$(nproc)
